.\" Manpage for onie-bisdn-upgrade.
.\" File an issue at https://github.com/bisdn/meta-switch/issues to correct
.\" errors or typos.
.TH ONIE-BISDN-UPGRADE 8 "23 May 2024" "" "BISDN Linux User Manual"
.SH NAME
onie-bisdn-upgrade \- upgrade or reinstall BISDN Linux
.SH SYNOPSIS
.B onie-bisdn-upgrade
[\fI\,OPTION\/\fR] [\fI\,IMAGEURL\/\fR]
.SH DESCRIPTION
.PP
\fIonie-bisdn-upgrade\fP will upgrade BISDN Linux.
.TP
[\fI\,IMAGEURL\/\fR]
.nf
URL of an installable BISDN Linux image
(e.g. http://repo.bisdn.de/pub/onie/generic-x86-64/onie-bisdn-generic-x86-64-v5.1.1.bin)
.fi
.TP
\fB\-y\fR
automatically answer yes to all questions (use with caution, system is going to reboot and configuration files might get lost)
.TP
\fB\-d\fR
download image before rebooting; useful in DHCP-less environments, or if the
image is not available via a protocol handled by ONIE's \fIwget\fP
.TP
\fB\-h\fR
display help and exit
.TP
.SH EXAMPLES
.TP
\fBonie-bisdn-upgrade http://repo.bisdn.de/pub/onie/generic-x86-64/onie-bisdn-generic-x86-64-v5.1.1.bin\fP
.SH SEE ALSO
onie-bisdn-uninstall(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Man page originally written by Pierluigi Greto <pierluigi.greto@bisdn.de>.
