.\" Manpage for onie-bisdn-uninstall.
.\" Contact pierluigi.greto@bisdn.de to correct errors or typos.
.TH man 8 "30 January 2019" "1.0" "onie-bisdn-uninstall man page"
.SH NAME
onie-bisdn-uninstall \- will uninstall BISDN Linux
.SH SYNOPSIS
.B onie-bisdn-uninstall
[\fI\,OPTION\/\fR]
.SH DESCRIPTION
.PP
onie-bisdn-uninstall will uninstall BISDN Linux
.TP
\fB\-y\fR
automatically answer yes to all questions (use with caution, since all configuration files are going to be deleted)
.TP
\fB\-h\fR
display help and exit
.TP
.SH SEE ALSO
onie-bisdn-upgrade(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Man page originally written by Pierluigi Greto <pierluigi.greto@bisdn.de>.
