.\" Manpage for onie-bisdn-upgrade.
.\" File an issue at https://github.com/bisdn/meta-switch/issues to correct
.\" errors or typos.
.TH ONIE-BISDN-UPGRADE 8 "23 May 2024" "" "BISDN Linux User Manual"
.SH NAME
onie-bisdn-upgrade \- upgrade or reinstall BISDN Linux
.SH SYNOPSIS
.B onie-bisdn-upgrade
[\fI\,OPTION\/\fR] [\fI\,IMAGEURL\/\fR]
.SH DESCRIPTION
.PP
\fIonie-bisdn-upgrade\fP initiates the installation of a new BISDN
Linux image on the switch.

The storage device is erased during the upgrade process. All files not
explicitly configured for retention will be deleted.

BISDN Linux has a backup configuration file, to keep specified user files
during the upgrade process.

To list files that will be preserved, run the following command:

.RS
.nf
\fIgrep -hv "^#" /var/lib/opkg/info/*.conffiles /etc/default/{system,user}-backup.txt\fP
.fi
.RE

Each line contains the path to a file (or directory) that should be kept,
unless the line starts with the \fI-\fP character which indicates that
the file should be deleted.

Files are only kept if they are listed in the above output without the
leading \fI-\fP.

Note: deletion takes precedence, files and subdirectories cannot be included
from a path marked for deletion.

To add a file to the list of retained files, add the path to the file to
\fI\%/etc/default/user-backup.txt\fP.

Any symbolic links listed in user-backup.txt will be ignored. Symlinks
within included directories will be kept.

.SH OPTIONS
.TP
[\fI\,IMAGEURL\/\fR]
.nf
URL of an installable BISDN Linux image
(e.g. http://repo.bisdn.de/pub/onie/generic-x86-64/onie-bisdn-generic-x86-64-v5.1.1.bin)
.fi
.TP
\fB\-y\fR
automatically answer yes to all questions (use with caution, system is going to reboot and configuration files might get lost)
.TP
\fB\-d\fR
download image before rebooting; useful in DHCP-less environments, or if the
image is not available via a protocol handled by ONIE's \fIwget\fP
.TP
\fB\-h\fR
display help and exit
.TP
.SH EXAMPLES
.TP
\fBonie-bisdn-upgrade http://repo.bisdn.de/pub/onie/generic-x86-64/onie-bisdn-generic-x86-64-v5.1.1.bin\fP
.SH SEE ALSO
onie-bisdn-uninstall(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Man page originally written by Pierluigi Greto <pierluigi.greto@bisdn.de>.
