.\" Manpage for onie-bisdn-rescue.
.\" Contact daniel.fritzsche@bisdn.de to correct errors or typos.
.TH man 8 "13 January 2020" "1.0" "onie-bisdn-uninstall man page"
.SH NAME
onie-bisdn-rescue \- boot into ONIE-rescue mode
.SH SYNOPSIS
.B onie-bisdn-rescue
[\fI\,OPTION\/\fR]
.SH DESCRIPTION
.PP
onie-bisdn-rescue boot into ONIE-rescue mode
.TP
\fB\-y\fR
automatically answer yes to all questions (use with caution, since all configuration files are going to be deleted)
.TP
\fB\-h\fR
display help and exit
.TP
.SH SEE ALSO
onie-bisdn-upgrade(1)
onie-bisdn-uninstall(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Man page originally written by Daniel Fritzsche <daniel.fritzsche@bisdn.de>.
