#!/bin/bash

# Copyright (C) 2019 Daniel Fritzsche of BISDN GmbH
# Bash script to upgrade BISDN Linux to a new image.

set -e

USAGE="Upgrade BISDN Linux
usage: $(basename "$0") [OPTIONS] [IMAGEURL]

[OPTIONS]
-h show this message
-y automatically answer yes to all questions (use with caution, system is going to reboot and configuration files might get lost)

[IMAGEURL] URL of an installable BISDN Linux image
           example: http://repo.bisdn.de/ftp/pub/onie/onie-bisdn-agema-ag7648.bin
	   example: $(basename "$0") http://repo.bisdn.de/ftp/pub/onie/onie-bisdn-agema-ag7648.bin
"

NEED_CONFIRM=true

while getopts "hy" o; do
  case $o in
    h) echo "$USAGE";
       exit 0;;
    y) # yes to all answers
       NEED_CONFIRM=false;;
    *) echo "Unknown parameter passed, printing help";
       echo "$USAGE";
       exit 1;;
  esac
done

if [[ $EUID -ne 0 ]]; then
   echo -e "Please run this program as root\nExiting" 1>&2
   exit 1
fi

if [[ ${NEED_CONFIRM} == false ]]; then shift;
fi;

case $# in
    0)
      echo "Unsufficient parameters passed!";
      echo "$USAGE"; exit 1;;
    1)
      INSTALL_FILE=$1;;
    *)
      echo "Too many parameters passed"; exit 1;;
esac;

if [ "${NEED_CONFIRM}" = true ]; then
  read -p "Upgrading BISDN Linux to install-source: ${INSTALL_FILE} using Client-IP-cfg: dhcp! Please confirm system reboot: [y/N] " yn
  case $yn in
    [Yy]* ) ;;
    * ) echo "Operation aborted.";
        exit 0;;
  esac
fi

if [ -f /etc/fw_env.config ]; then
  debugargs="install_url=${INSTALL_FILE}"
  fw_setenv onie_debugargs "$debugargs"
  fw_setenv onie_boot_reason "install"
else
  MNT_DIR="/mnt/onie-boot"
  mountpoint -q ${MNT_DIR} || mount ${MNT_DIR}
  ${MNT_DIR}/onie/tools/bin/onie-boot-mode -q -o install
  grub-reboot ONIE

  sed -i "/export ONIE_EXTRA_CMDLINE_LINUX/ i ONIE_EXTRA_CMDLINE_LINUX=\""\${ONIE_EXTRA_CMDLINE_LINUX}" install_url=${INSTALL_FILE}\" " ${MNT_DIR}/grub/grub.cfg
fi

systemctl reboot
