#!/bin/bash

set -e

USAGE="$(basename "$0") -- this will uninstall BISDN-Linux. Options:
[-h] shows this message.
[-y] will uninstall without asking confirm.
"


NEED_CONFIRM=true


while getopts "hy" o; do
  case $o in
    h)
      echo "$USAGE";
      exit 0;;
    y) # yes to all answers
      NEED_CONFIRM=false
    ;;
    * ) echo "Operation aborted.";
        exit 0;;
  esac
done

if [ "${NEED_CONFIRM}" = true ]
then
  read -p "Uninstall BISDN-Linux? [y/N] " yn
  case $yn in
    [Yy]* ) ;;
    * ) echo "Operation aborted.";
        exit 0;;
  esac
fi

MNT_DIR="/mnt/onie-boot"
mountpoint -q ${MNT_DIR} || mount ${MNT_DIR}
${MNT_DIR}/onie/tools/bin/onie-boot-mode -q -o uninstall
grub-reboot ONIE

systemctl reboot
