#!/bin/bash

# Copyright (C) 2019 Daniel Fritzsche of BISDN GmbH
# Bash script to upgrade BISDN Linux to a new image.

set -e

USAGE="Upgrade BISDN Linux
usage: $(basename "$0") [OPTIONS] [IMAGEURL]

[OPTIONS]
-h show this message
-d download image and use localfs discovery for installation
-y automatically answer yes to all questions (use with caution, system is going to reboot and configuration files might get lost)

[IMAGEURL] URL of an installable BISDN Linux image
           Example: http://repo.bisdn.de/pub/onie/generic-x86-64/onie-bisdn-generic-x86-64-v5.1.1.bin

Example usage:
$(basename "$0") http://repo.bisdn.de/pub/onie/generic-x86-64/onie-bisdn-generic-armel-iproc-v5.1.1.bin

For additional information, see the man page for onie-bisdn-upgrade(1).
"

NEED_CONFIRM=true
DOWNLOAD=false

while getopts "dhy" o; do
  case $o in
    d) DOWNLOAD=true;;
    h) echo "$USAGE";
       exit 0;;
    y) # yes to all answers
       NEED_CONFIRM=false;;
    *) echo "Unknown parameter passed, printing help";
       echo "$USAGE";
       exit 1;;
  esac
done

if [[ $EUID -ne 0 ]]; then
   echo -e "Please run this program as root\nExiting" 1>&2
   exit 1
fi

shift $((OPTIND-1))

case $# in
    0)
      echo "Unsufficient parameters passed!";
      echo "$USAGE"; exit 1;;
    1)
      INSTALL_FILE=$1;;
    *)
      echo "Too many parameters passed"; exit 1;;
esac;

if [ "${NEED_CONFIRM}" = true ]; then
  cat << EOF
Upgrading BISDN Linux from ${INSTALL_FILE}.

############################################################################
# ONLY FILES CONFIGURED FOR RETENTION WILL BE KEPT!                        #
#                                                                          #
# For additional information, see the man page for onie-bisdn-upgrade(1).  #
############################################################################
EOF
  read -p "Reboot the system and upgrade BISDN Linux? [y/N] " yn
  case $yn in
    [Yy]* ) ;;
    * ) echo "Operation aborted.";
        exit 0;;
  esac
fi

if [ "${DOWNLOAD}" = true ]; then
  curl "$INSTALL_FILE" > /onie-installer
  debugargs=
else
  debugargs="install_url=${INSTALL_FILE}"
fi

if [ -f /etc/fw_env.config ]; then
  fw_setenv onie_debugargs "$debugargs"
  fw_setenv onie_boot_reason "install"
else
  MNT_DIR="/mnt/onie-boot"
  mountpoint -q ${MNT_DIR} || mount ${MNT_DIR}
  ${MNT_DIR}/onie/tools/bin/onie-boot-mode -q -o install
  grub-reboot ONIE

  sed -i "/export ONIE_EXTRA_CMDLINE_LINUX/ i ONIE_EXTRA_CMDLINE_LINUX=\""\${ONIE_EXTRA_CMDLINE_LINUX}" $debugargs\" " ${MNT_DIR}/grub/grub.cfg
fi

systemctl reboot
