#!/bin/bash

# Copyright (C) 2019 Daniel Fritzsche of BISDN GmbH
# Bash script to upgrade BISDN Linux to a new image.

set -e

USAGE="Upgrade BISDN Linux
usage: $(basename "$0") [OPTIONS] [IMAGEURL [IPCONFIG]]

[OPTIONS]
-h show this message
-y automatically answer yes to all questions (use with caution, system is going to reboot and configuration files might get lost)

[IMAGEURL] URL of an installable BISDN Linux image
           example: http://repo.bisdn.de/ftp/pub/onie/onie-bisdn-agema-ag7648.bin

[IPCONFIG] IP address (IP), gateway (GW) and netmask (NETMASK) of an interface, must be omitted when DHCP is available!
           format: <IP>::<GW>:<NETMASK>
	   example: 10.250.7.177::10.250.7.1:255.255.255.0
	   'current' takes the current IP/GW/NETMASK of the 'enp0s20f0' interface
	   example: $(basename "$0") http://repo.bisdn.de/ftp/pub/onie/onie-bisdn-agema-ag7648.bin current
"

NEED_CONFIRM=true

while getopts "hy" o; do
  case $o in
    h) echo "$USAGE";
       exit 0;;
    y) # yes to all answers
       NEED_CONFIRM=false;;
    *) echo "Unknown parameter passed, printing help";
       echo "$USAGE";
       exit 1;;
  esac
done

if [[ ${NEED_CONFIRM} == false ]]; then shift;
fi;

case $# in
    0)
      echo "Unsufficient parameters passed!";
      echo "$USAGE"; exit 1;;
    1)
      INSTALL_FILE=$1; IP="dhcp";;
    2)
      INSTALL_FILE=$1;
      if [[ $2 == "current" ]]; then
        INTF="enp0s20f0";
        IP_ADDR=$(ip -j -4 a l dev ${INTF} | jq -r '.[].addr_info[0].local //empty');
        GW=$(ip -j -4 r l dev ${INTF} | jq -r '.[0].gateway // empty');
        PREFIXLEN=$(ip -j -4 a l dev ${INTF} | jq -r '.[].addr_info[0].prefixlen // empty');
        eval $(ipcalc -m ${IP_ADDR}"/"${PREFIXLEN});
        IP="${IP_ADDR}::${GW}:${NETMASK}::eth0:none";
        else
        IP="$2::eth0:none";
      fi;;
    *)
      echo "Too many parameters passed"; exit 1;;
esac;

if [ "${NEED_CONFIRM}" = true ]; then
  read -p "Upgrading BISDN Linux to install-source: ${INSTALL_FILE} using Client-IP-cfg: ${IP}! Please confirm system reboot: [y/N] " yn
  case $yn in
    [Yy]* ) ;;
    * ) echo "Operation aborted.";
        exit 0;;
  esac
fi

if [ -f /etc/fw_env.config ]; then
  if [[ -n "${IP}" && "${IP}" != "dhcp" ]]; then
    boot_reason="install ip=${IP} install_url=${INSTALL_FILE}"
  else
    boot_reason="install install_url=${INSTALL_FILE}"
  fi
  fw_setenv onie_boot_reason "$boot_reason"
else
  MNT_DIR="/mnt/onie-boot"
  mountpoint -q ${MNT_DIR} || mount ${MNT_DIR}
  ${MNT_DIR}/onie/tools/bin/onie-boot-mode -q -o install
  grub-reboot ONIE

  if [[ -n "${IP}" && "${IP}" != "dhcp" ]]; then
    sed -i "/export ONIE_EXTRA_CMDLINE_LINUX/ i ONIE_EXTRA_CMDLINE_LINUX=\""\${ONIE_EXTRA_CMDLINE_LINUX}" ip=${IP} install_url=${INSTALL_FILE}\" " ${MNT_DIR}/grub/grub.cfg
  else
    sed -i "/export ONIE_EXTRA_CMDLINE_LINUX/ i ONIE_EXTRA_CMDLINE_LINUX=\""\${ONIE_EXTRA_CMDLINE_LINUX}" install_url=${INSTALL_FILE}\" " ${MNT_DIR}/grub/grub.cfg
  fi;
fi

systemctl reboot
